version: '3.8'

services:
  web:
    image: php:7.4-apache
    container_name: php-apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: eclass
      MYSQL_USER: parc
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/eclass.sql:/docker-entrypoint-initdb.d/eclass.sql:ro

volumes:
  db_data:
